/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: PositionControllerTilt
 *  expmt: Jiwy
 *  date:  June 7, 2021
 *  time:  10:45:11 AM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
